# Generated by Django 5.2.15 on 2026-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('posicao', models.CharField(max_length=30)),
                ('clube', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('foto', models.ImageField(upload_to='jogadores/')),
                ('capitao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('continente', models.CharField(max_length=50)),
                ('federacao', models.CharField(max_length=100)),
                ('tecnico', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=100)),
                ('fundacao', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('bandeira', models.ImageField(upload_to='bandeiras/')),
                ('foto', models.ImageField(upload_to='selecao/')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competicao', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('colocacao', models.CharField(max_length=50)),
            ],
        ),
    ]
