# Generated by Django 5.2.15 on 2026-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecao',
            name='bandeira',
        ),
        migrations.RemoveField(
            model_name='selecao',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='titulo',
            name='colocacao',
        ),
        migrations.AddField(
            model_name='titulo',
            name='resultado',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jogadores/'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('GOL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('MEI', 'Meia'), ('ATA', 'Atacante')], max_length=3),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='ano',
            field=models.CharField(max_length=50),
        ),
    ]
